"""Extract _NODE_CUSTOM_ICONS from upstream ct_const.h for Dart codegen."""
import re
import sys

CHERRY = {
    "CHERRY_BLACK": "cherry_black",
    "CHERRY_BLUE": "cherry_blue",
    "CHERRY_CYAN": "cherry_cyan",
    "CHERRY_GREEN": "cherry_green",
    "CHERRY_GRAY": "cherry_grey",
    "CHERRY_ORANGE": "cherry_orange",
    "CHERRY_ORANGE_DARK": "cherry_orange_dark",
    "CHERRY_PURPLE": "cherry_purple",
    "CHERRY_RED": "cherry_red",
    "CHERRY_SHERBERT": "cherry_sherbert",
    "CHERRY_YELLOW": "cherry_yellow",
}


def main() -> None:
    path = sys.argv[1]
    all_lines = open(path, encoding="utf-8").readlines()
    start = None
    for i, line in enumerate(all_lines):
        if "_NODE_CUSTOM_ICONS {" in line:
            start = i + 1
            break
    if start is None:
        raise SystemExit("no _NODE_CUSTOM_ICONS { line")
    names: list[str | None] = []
    for line in all_lines[start:]:
        line = line.strip()
        if line.startswith("};"):
            break
        if not line.endswith(","):
            line = line.rstrip()
        if not line:
            continue
        # strip trailing comma and comments
        line = line.split("//")[0].strip().rstrip(",").strip()
        if not line:
            continue
        raw = line
        tok = raw.strip()
        if not tok or tok.startswith("//"):
            continue
        if tok == "nullptr":
            names.append(None)
        elif tok.startswith('"'):
            names.append(tok.strip('"'))
        elif tok in CHERRY:
            names.append(CHERRY[tok])
        else:
            raise SystemExit(f"unknown token: {tok}")
    print(f"// Generated by tool/gen_stock_icons.py - {len(names)} entries")
    print("const List<String?> kCherrytreeStockIconNames = [")
    for n in names:
        if n is None:
            print("  null,")
        else:
            print(f"  {repr(n)},")
    print("];")


if __name__ == "__main__":
    main()
